version: "3.8"
 
services:
  nifi:
    image: apache/nifi:1.19.1
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=AdminPassword123!
    volumes:
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - ../hadoop-conf:/etc/hadoop/conf
    restart: unless-stopped
 
volumes:
  nifi_content:
  nifi_flowfile:
  nifi_provenance:
  nifi_state:
  
